import 'package:hive/hive.dart';

part 'vehicle_profile.g.dart'; // generated by build_runner — see README setup steps

@HiveType(typeId: 0)
class VehicleProfile extends HiveObject {
  @HiveField(0)
  String name;

  // Physical spec, from manufacturer + your benchmark test
  @HiveField(1)
  double systemVoltage;

  @HiveField(2)
  double batteryAh;

  @HiveField(3)
  double motorWattPeak;

  // Derived from your 90km real-world eco-mode discharge test (Dhaka
  // city riding, with breaks between trip legs) at 18.4 Wh/km overall
  @HiveField(4)
  double baseWhPerKm;

  // Physics constants — kept at sane baseline values. Don't distort
  // these to force-fit a single data point (see dragCoefficientArea
  // comment below) — use congestionOverheadWhPerKm for that instead.
  @HiveField(5)
  double crr; // rolling resistance coefficient

  @HiveField(6)
  double dragCoefficientArea; // Cd * A — keep near 0.5-0.7, physically sane

  @HiveField(7)
  double efficiency; // motor/controller efficiency

  @HiveField(8)
  double socHealthFactor;

  // --- Mass breakdown ---
  // Previously the engine was accidentally fed rider weight alone as
  // "total mass" -- that's wrong, rolling resistance depends on the
  // FULL system mass (vehicle + rider + passenger).
  @HiveField(9)
  double vehicleWeightKg; // 103-105kg for the F52, using midpoint

  @HiveField(10)
  double defaultRiderWeightKg; // 68kg

  // --- Congestion / stop-start overhead ---
  // Steady-state cruise physics (rolling resistance + drag) badly
  // underestimates consumption in heavy stop-and-go traffic, because
  // it doesn't model repeated acceleration from a stop, braking losses
  // (no regen assumed), or idle draw while stationary in congestion.
  // Rather than distorting dragCoefficientArea to hide this, it's
  // modeled as a separate additive term that only applies below
  // congestionSpeedThresholdKmh. Calibrated from your Mirpur DOHS ->
  // Tongi College Gate commute (~12.5km / ~37.5min, avg 20km/h,
  // heavy stop-and-go): ~6.5 Wh/km on top of the physics prediction.
  @HiveField(11)
  double congestionOverheadWhPerKm;

  @HiveField(12)
  double congestionSpeedThresholdKmh;

  // The bike's real top speed (full throttle, not your usual eco/1st
  // gear cap) — used as the max reference for the speed gauge, so the
  // dial reflects the vehicle's actual capability rather than
  // whichever riding mode you happen to be in today.
  @HiveField(13)
  double topSpeedKmh;

  VehicleProfile({
    this.name = 'TailG F52 Red Rabbit',
    this.systemVoltage = 72.0,
    this.batteryAh = 23.0,
    this.motorWattPeak = 1200.0,
    this.baseWhPerKm = 18.4,
    this.crr = 0.015,
    this.dragCoefficientArea = 0.6,
    this.efficiency = 0.85,
    this.socHealthFactor = 1.0,
    this.vehicleWeightKg = 104.0,
    this.defaultRiderWeightKg = 68.0,
    this.congestionOverheadWhPerKm = 6.5,
    this.congestionSpeedThresholdKmh = 25.0,
    this.topSpeedKmh = 50.0,
  });

  double totalEnergyWh() => systemVoltage * batteryAh * socHealthFactor;
}
